### ISSUE TITLE
test 12

### ISSUE THREAD

**Issue by serhiikutsko** [SergeyKutsko/todo#12]

**Comment by zerocratsubs** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) please, pay attention to this issue

**Comment by zerocratsubs** [comment]
Job [#12](https://github.com/sergeykutsko/todo/issues/12) is now in scope, role is `DEV`

**Comment by zerocratsubs** [comment]
The job [#12](https://github.com/sergeykutsko/todo/issues/12) assigned to @serhiikutsko[/z](https://www.0crat.com/u/serhiikutsko), here is [why](https://www.0crat.com/footprint/CKLLW3K8Q/5b614b50-4352-40ad-ad7d-ebf56e5a6733); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by zerocratsubs** [comment]
Job `gh:sergeykutsko/todo#12` already assigned to @serhiikutsko, can't assign to @serhiikutsko

**Comment by zerocratsubs** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 18813@ip-172-31-12-121, thread: pool-15-thread-1
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/equity/shares/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<equity x..170..cracy.com/0.66/xsd/pm/cost/equity.xsd"/>\uA': Index (0) is out of bounds (size=0)
```

[0.30.7](https://github.com/zerocracy/farm): CID: [bc57f713-5d1a-4f31-af66-e30387ab94b0](https://www.0crat.com/footprint/CKLLW3K8Q/bc57f713-5d1a-4f31-af66-e30387ab94b0), Type: "Transfer shares"

**Comment by zerocratsubs** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @serhiikutsko[/z](https://www.0crat.com/u/serhiikutsko)

**Comment by zerocratsubs** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by zerocratsubs** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by zerocratsubs** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) please, pay attention to this issue

**Comment by zerocratsubs** [comment]
GitHub issue is still open, won't close

**Comment by zerocratsubs** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) I see that you unassigned this issue; the order is still assigned to @serhiikutsko[/z](https://www.0crat.com/u/serhiikutsko) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)
